# -*- sh -*-
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="random"
DEFAULT_USER="sourdzl"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to disable command auto-correction.
# DISABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
    # Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
    # Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git zsh-syntax-highlighting colorize cp tmux tmuxinator vi-mode osx battery)

source $ZSH/oh-my-zsh.sh 

# User configuration
export PATH="/usr/local/bin:$PATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

source ~/.zsh_profile

# make cd auto ls
function cd {
    builtin cd "$@" && ls -F
        }

# compsys initialization
autoload -U compinit
compinit

# show completion menu when number of options is at least 2
zstyle ':completion:*' menu select=2
alias npm-exec='PATH=$(npm bin):$PATH'
source ~/.fzf.zsh

fd() {
  local dir
  dir=$(find ${1:-*} -path '*/\.*' -prune \
                  -o -type d -print 2> /dev/null | fzf +m) &&
  cd "$dir"
}

setopt NO_NOMATCH

# Tmux session handling
function fzf_tmux_session {
    selection_string=$(tmux list-windows | fzf)
    session_number=$(ruby -e "print '${selection_string}'[/^(\d+):/, 1]")
    tmux select-window -t :$session_number
}
alias fzftmux=fzf_tmux_session

export TERM=xterm-256color


# replace less with vimpager for coloration
export PAGER=/usr/local/bin/vimpager
alias less=$PAGER
alias zless=$PAGER
